FROM debian:bullseye
RUN apt-get update && apt-get -y install apt-utils
RUN apt-get update && apt-get -y install \
    gawk wget git-core diffstat unzip texinfo gcc-multilib \
    build-essential chrpath socat cpio python python3 \
    python3-pip python3-pexpect xz-utils debianutils \
    iputils-ping libsdl1.2-dev xterm tar locales bmap-tools \
    screen nano libncurses5-dev libncursesw5-dev \
    zstd lz4 procps dnf
RUN pip3 install kas
RUN rm /bin/sh && ln -s bash /bin/sh
ENV LANG=en_US.UTF-8
RUN apt-get install -y locales && \
    sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=$LANG
ARG USER_NAME=builduser
ARG host_uid=1001
ARG host_gid=1001
RUN groupadd -g $host_gid $USER_NAME && \
    useradd -g $host_gid -m -s /bin/bash -u $host_uid $USER_NAME
USER $USER_NAME
COPY docker-kas /usr/bin/docker-kas
CMD ["/bin/bash"]
